/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.DatabaseProvider.iDB2.ConfigurationService;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.DatabaseProvider.iDB2 {

    public class iDB2IntegrationDatabaseProvider : BaseDatabaseProvider {

        private readonly IProviderProperties properties;

        public static readonly IDatabaseProvider Instance = new iDB2IntegrationDatabaseProvider();

        public iDB2IntegrationDatabaseProvider() {
            properties = new iDB2ProviderProperties(this);
        }

        public override DatabaseProviderKey Key {
            get { return DatabaseProviderKey.Deserialize("iDB2"); }
        }

        public override IProviderProperties Properties {
            get { return properties; }
        }

        public override IDatabaseServices GetIntegrationDatabaseServices(IRuntimeDatabaseConfiguration databaseConfiguration) {
            return new iDB2DatabaseServices(databaseConfiguration);
        }

        public override IIntegrationDatabaseConfiguration CreateEmptyIntegrationDatabaseConfiguration() {
            return new iDB2DatabaseConfiguration();
        }
    }
}
