/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.RuntimePlatform.Callbacks {

    public interface ILibraryCallbackHandler {

        /// <summary>
        /// Returns the Html code that will be injected in each Web Page request through the runtime callback engine
        /// </summary>
        /// <param name="app"></param>
        /// <param name="session"></param>
        /// <param name="locale"></param>
        /// <param name="data"></param>
        /// <returns>A String with the the Html code to be used in the Web Page request.</returns>
        string GetDynamicHtmlInjection(AppInfo app, SessionInfo session, string locale, string data);
	}

}