/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.RuntimePlatform.Sql {

    public sealed class PrepareQueryForCount {

        public static bool IsSelectStatement(string sql) {
            return StringUtils.ValidQueryForCountMultiLineRegex.IsMatch(sql);
        }
    }

    public class InvalidQueryForCount : DataBaseException {
        public InvalidQueryForCount(string sql)
            : base("Could not calculate the query count. Actual SQL used was: " + sql) {
        }
    }
}