/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

namespace OutSystems.RuntimeCommon.Cryptography.Implementations.Crypt
{
    /// <summary>
    /// NOTE: This algorithm is FIPS compliant...
    /// </summary>
    public class RsaKeyPair {

        private RsaPrivateKey privateKey;

        private RsaKey publicKey;

        public RsaKeyPair(RsaPrivateKey privateKey, RsaKey publicKey) {
            this.privateKey = privateKey;
            this.publicKey = publicKey;
        }

        public RsaPrivateKey PrivateKey {
            get {
                return privateKey;
            }
        }

        public RsaKey PublicKey {
            get {
                return publicKey;
            }
        }
    }
}