/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.Platform.DatabaseObjects;

namespace OutSystems.HubEdition.DatabaseProvider.MySQL.Platform.DatabaseObjects {
    public class MySQLPlatformTableSourceTriggerInfo : IPlatformTableSourceEventTriggerInfo {

        public MySQLPlatformTableSourceTriggerInfo(ITableSourceInfo tableSource, string name) {
            TableSource = tableSource;
            Name = name;
        }

        public ITableSourceInfo TableSource { get; private set; }
        public string Name { get; private set; }
    }
}
