/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using NLog;
using OutSystems.Logging.LogDefinition;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OutSystems.Logging.Implementations {
    public class OutSystemsLogEventInfo : LogEventInfo {

        public AbstractLogDefinition Log { get; }

        public OutSystemsLogEventInfo(AbstractLogDefinition log) : base(){
            this.Log = log;
        }
    }
}
