/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.IO;
using OutSystems.RuntimeCommon.Extensibility.Plugins;

namespace OutSystems.RuntimeCommon.Caching {

    public sealed class CachePluginProvider : AbstractPluginProvider<string, ICachePlugin> {
        public const string CachePluginsSubFolderName = "caching";

        protected override IEnumerable<DirectoryInfo> PluginDirectories {
            get {
                return DefaultPluginDirectories<CachePluginProvider>(CachePluginsSubFolderName, isRuntimePlugin: true);
            }
        }
        
        protected override string PluginsNameMask {
            get {
                return "*.Plugin.*.dll";
            }
        }
        
        protected override String GetKey(ICachePlugin p) {
            return p.Key;
        }

        public CachePluginProvider() {
            LoadPlugins((e, s) => {
                OSTrace.Info(s, e);
            });
        }
    }
}
