/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.IO;
using System.Web.UI;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.WebWidgets {
    public sealed class HtmlTextWriterOverriderForWebControls : HtmlTextWriter {

        private readonly HtmlTextWriterAttribute[] _attributesToOverride;
        private readonly string[] _overrideValues;

        public HtmlTextWriterOverriderForWebControls(TextWriter writer, HtmlTextWriterAttribute[] attributesToOverride, string[] overrideValues)
            : base(writer) {
            _attributesToOverride = attributesToOverride;
            _overrideValues = overrideValues;
        }

        public override void AddAttribute(HtmlTextWriterAttribute key, string value) {
            for (int i = 0; i < _attributesToOverride.Length; ++i) {
                if (key == _attributesToOverride[i]) {
                    base.AddAttribute(key, _overrideValues[i]);
                    return;
                }
            }
            base.AddAttribute(key, value);
        }

    }
}