/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;

namespace OutSystems.PluginAPI.PluginConfiguration {
    [AttributeUsage(AttributeTargets.Property)]
    public class PluginConfigurationAttribute: Attribute, IPluginConfigurationParameter {
        /// <summary>
        /// Defines if the attribute should be encrypted
        /// </summary>
        public bool Encrypt { get; set; }
        
        /// <summary>
        /// Defines if this parameter should be persisted
        /// </summary>
        public bool Persist { get; set; } = true;
    }
}
