/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.DatabaseProvider.Oracle.DatabaseObjects {
    public class TableSourceColumnInfo : ITableSourceColumnInfo {

        private readonly AutoNumberColumnInfo autoNumberInfo;

        private TableSourceColumnInfo(ITableSourceInfo tableSource, string name, IDataTypeInfo dataType, bool isMandatory, bool isPrimaryKey) {
            TableSource = tableSource;
            Name = name;
            DataType = dataType;
            IsMandatory = isMandatory;
            IsPrimaryKey = isPrimaryKey;
        }

        public TableSourceColumnInfo(ITableSourceInfo tableSource, string name, IDataTypeInfo dataType, bool isMandatory, bool isPrimaryKey,
                                     bool isAutoNumber) : this(tableSource, name, dataType, isMandatory, isPrimaryKey) {
            IsAutoGenerated = isAutoNumber;
        }

        public TableSourceColumnInfo(ITableSourceInfo tableSource, string name, IDataTypeInfo dataType, bool isMandatory, bool isPrimaryKey,
                                     AutoNumberColumnInfo autoNumberInfo) : this(tableSource, name, dataType, isMandatory, isPrimaryKey) {

            this.autoNumberInfo = autoNumberInfo;
            // The auto-number is only valid if all fields are filled
            IsAutoGenerated = autoNumberInfo != null && !autoNumberInfo.SequenceName.IsNullOrEmpty() && !autoNumberInfo.TriggerName.IsNullOrEmpty();
        }

        public ITableSourceInfo TableSource { get; private set; }
        public string Name { get; private set; }
        public virtual IDataTypeInfo DataType { get; private set; }
        public bool IsMandatory { get; private set; }
        public bool IsPrimaryKey { get; private set; }
        public bool IsAutoGenerated { get; private set; }
        
        public string AutoNumberTriggerName {
            get { return autoNumberInfo != null ? autoNumberInfo.TriggerName : null; }            
        }

        public string AutoNumberSequenceName {
            get { return autoNumberInfo != null ? autoNumberInfo.SequenceName : null; }
        }
    }
}
