/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Xml;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Db;
using OutSystems.HubEdition.RuntimePlatform.Web;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.WebWidgets {
    public class ListBoxRtWidget : RtWidget, IListBoxRtWidget {
        public IOSList list;
        public IOSList List {
            get { return this.list; }
            set { this.list = value; }
        }

        public override void InnerToXml(XmlElement widgetElem, int detailLevel) {
            if (List != null)
                List.ToXml(this, widgetElem, "List", detailLevel - 1);
        }

        public override void InnerEvaluateField(VarValue variable, string field) {
            if (field == "list")
                variable.Value = List;
        }
    }
}
