/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

namespace OutSystems.PluginAPI.PluginConfiguration.Introspection {
    /// <summary>
    /// Interface for annotated parameter.
    /// </summary>
    public interface IUserDefinedPluginParameter: IPluginParameter {
        bool Visible { get; }
        string Label { get; }
        string Example { get; }
        bool Mandatory { get; }
        int Order { get; }
        string Region { get; }
        bool IsPassword { get; }
        bool Multiline { get; }
        string AutoCompleteExpression { get; }
    }
}
